"""add_sharing_tables

Revision ID: edd56e80ba2e
Revises: 9d501af998a8
Create Date: 2026-02-19 16:39:49.268954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd56e80ba2e'
down_revision: Union[str, Sequence[str], None] = '9d501af998a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_access',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('can_reply', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_access_conversation_id'), 'conversation_access', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_access_id'), 'conversation_access', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_access_user_id'), 'conversation_access', ['user_id'], unique=False)
    op.create_table('shared_conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('shared_by_user_id', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('share_type', sa.Enum('public_link', 'private', name='share_type'), nullable=False),
    sa.Column('allow_replies', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_conversations_conversation_id'), 'shared_conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shared_conversations_id'), 'shared_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_shared_conversations_share_token'), 'shared_conversations', ['share_token'], unique=True)
    op.create_index(op.f('ix_shared_conversations_shared_by_user_id'), 'shared_conversations', ['shared_by_user_id'], unique=False)
    op.create_table('conversation_forks',
    sa.Column('original_conversation_id', sa.UUID(), nullable=True),
    sa.Column('forked_conversation_id', sa.UUID(), nullable=False),
    sa.Column('forked_by_user_id', sa.UUID(), nullable=False),
    sa.Column('forked_at_message_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forked_at_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forked_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forked_conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_forks_forked_by_user_id'), 'conversation_forks', ['forked_by_user_id'], unique=False)
    op.create_index(op.f('ix_conversation_forks_forked_conversation_id'), 'conversation_forks', ['forked_conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_forks_id'), 'conversation_forks', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_forks_original_conversation_id'), 'conversation_forks', ['original_conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_forks_original_conversation_id'), table_name='conversation_forks')
    op.drop_index(op.f('ix_conversation_forks_id'), table_name='conversation_forks')
    op.drop_index(op.f('ix_conversation_forks_forked_conversation_id'), table_name='conversation_forks')
    op.drop_index(op.f('ix_conversation_forks_forked_by_user_id'), table_name='conversation_forks')
    op.drop_table('conversation_forks')
    op.drop_index(op.f('ix_shared_conversations_shared_by_user_id'), table_name='shared_conversations')
    op.drop_index(op.f('ix_shared_conversations_share_token'), table_name='shared_conversations')
    op.drop_index(op.f('ix_shared_conversations_id'), table_name='shared_conversations')
    op.drop_index(op.f('ix_shared_conversations_conversation_id'), table_name='shared_conversations')
    op.drop_table('shared_conversations')
    op.drop_index(op.f('ix_conversation_access_user_id'), table_name='conversation_access')
    op.drop_index(op.f('ix_conversation_access_id'), table_name='conversation_access')
    op.drop_index(op.f('ix_conversation_access_conversation_id'), table_name='conversation_access')
    op.drop_table('conversation_access')
    # ### end Alembic commands ###
